#!/usr/bin/env python3


import os
import pathlib
import re
import subprocess
import sys

from pre_commit_vauxoo.pre_commit_vauxoo import SCOPE_ENVVAR, SCOPE_LAST_COMMIT, get_repo

ALLOWED_TAGS = {
    "ADD": "adding new modules or new major features",
    "CLA": "signing or updating the Contributor License Agreement",
    "CLN": "cleanup changes that improve code quality without changing behavior",
    "FIX": "bug fixes",
    "I18N": "translation or localization changes",
    "IMP": "incremental improvements to existing behavior",
    "MIG": "migrating a module or project changes to another Odoo version",
    "MERGE": "merging branches or bringing branch histories together",
    "MOVE": "moving or renaming resources, including moving content from one module to another",
    "MOV": "moving or renaming resources",
    "PERF": "performance improvements",
    "REF": "refactoring existing code without changing expected behavior",
    "REL": "release-related changes",
    "REM": "removing dead code, modules, views, or other resources",
    "REV": "reverting a previous change",
}
HEADER_RE = re.compile(r"^\[(?P<tags>[A-Z,\/]+)\] (?P<modules>[^:]+): (?P<summary>\S.*)$")
GIT_AUTOGENERATED_PREFIXES = ("Merge ", "Revert ")
SPECIAL_MODULE_NAMES = {"*", "various"}


def format_allowed_tags_help():
    lines = ["Allowed tags are:"]
    for tag, description in sorted(ALLOWED_TAGS.items()):
        lines.append(f"  [{tag}] {description}")
    return "\n".join(lines)


def split_targets(raw_value):
    return [item.strip() for item in re.split(r"[,/]", raw_value) if item.strip()]


def get_repo_root_modules(repo_root):
    return {
        entry
        for entry in os.listdir(repo_root)
        if pathlib.Path(os.path.join(repo_root, entry)).is_dir() and not entry.startswith(".")
    }


def target_exists(repo_root, target, repo_root_modules):
    if target in SPECIAL_MODULE_NAMES:
        return True
    if target in repo_root_modules:
        return True
    return pathlib.Path(os.path.join(repo_root, target)).is_file()


def validate_commit_message_header(header, repo_root=None):
    header = header.strip()
    if not header:
        return ["Commit message header is empty."]
    if header.startswith(GIT_AUTOGENERATED_PREFIXES):
        return []
    if header.startswith("[MERGE]"):
        return []

    match = HEADER_RE.match(header)
    if not match:
        return [
            "Invalid commit message header.",
            "Expected format: [TAG] module_name[,module_name2]: concise summary",
            "You can also use multiple tags or targets separated by ',' or '/'.",
            format_allowed_tags_help(),
        ]

    tags = split_targets(match.group("tags"))
    modules_raw = match.group("modules")
    summary = match.group("summary").strip()
    modules = split_targets(modules_raw)
    errors = []

    invalid_tags = [tag for tag in tags if tag not in ALLOWED_TAGS]
    if invalid_tags:
        errors.append(
            "Invalid tag(s): %s.\nUse one or more tags separated by ',' or '/'.\n%s"
            % (", ".join(f"[{tag}]" for tag in invalid_tags), format_allowed_tags_help())
        )
    if not tags:
        errors.append("At least one tag is required inside '[...]'.")
    if not modules:
        errors.append("At least one module or file target is required before ':'.")
    if not summary:
        errors.append("Commit summary cannot be empty.")

    if repo_root and modules:
        repo_root_modules = get_repo_root_modules(repo_root)
        invalid_modules = [module for module in modules if not target_exists(repo_root, module, repo_root_modules)]
        if invalid_modules:
            errors.append(
                "Unknown module or file target(s): %s. "
                "Use one or more targets separated by ',' or '/'. "
                "Each target must be '*', an existing root module directory, "
                "or an existing file path in the repository." % ", ".join(invalid_modules)
            )
    return errors


def check_commit_msg_file(commit_msg_file, repo_root=None):
    with pathlib.Path(commit_msg_file).open(encoding="utf-8") as commit_msg_fd:
        header = commit_msg_fd.readline()

    if repo_root is None:
        repo_root = get_repo()

    errors = validate_commit_message_header(header, repo_root=repo_root)
    if errors:
        for error in errors:
            print(f"{commit_msg_file} - {error}")
        return False
    return True


def git_ref_exists(ref_name, cwd=None):
    return not subprocess.call(["git", "show-ref", "--verify", "--quiet", ref_name], cwd=cwd)


def git_rev_exists(revision, cwd=None):
    """Whether a revision is resolvable, for the ones "show-ref --verify" can not check

    "HEAD~1" is not a ref, so it needs "rev-parse" instead: it does not exist on a
    repository whose only commit is the root one.
    """
    return not subprocess.call(
        ["git", "rev-parse", "--verify", "--quiet", revision],
        cwd=cwd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def get_git_remotes_with_urls(cwd=None):
    remote_names = subprocess.check_output(["git", "remote"], cwd=cwd).decode(sys.stdout.encoding).splitlines()
    remotes = {}
    for remote_name in remote_names:
        remote_url = (
            subprocess
            .check_output(["git", "config", "--get", f"remote.{remote_name}.url"], cwd=cwd)
            .decode(sys.stdout.encoding)
            .strip()
        )
        remotes[remote_name] = remote_url
    return remotes


def resolve_commit_message_base_ref(version, scope=None, cwd=None):
    """The revision the commits to validate are counted from

    Two questions are answered here, and both are asked by the file scopes too:

    * "--last-commit" only added or modified files in HEAD, so only the message of
      HEAD is validated, which is the "HEAD~1..HEAD" range.
    * every other scope compares against the stable branch named by VERSION. It is
      looked up as "<remote>/<VERSION>" on the remotes whose URL does not contain
      "dev" -- preferring "origin" -- because the dev fork is where the branch being
      validated lives, and its copy of stable is the stale one. Only when no remote
      has it does the local branch "<VERSION>" answer instead.
    """
    if scope is None:
        scope = os.environ.get(SCOPE_ENVVAR, "").strip()
    if scope == SCOPE_LAST_COMMIT:
        if git_rev_exists("HEAD~1", cwd=cwd):
            return "HEAD~1"
        print("HEAD has no parent, falling back to the stable branch for commit message validation")

    if not version:
        return ""

    remote_candidates = []
    for remote_name, remote_url in get_git_remotes_with_urls(cwd=cwd).items():
        if "dev" in remote_url.lower():
            print(f"Skipping remote {remote_name} because its URL contains 'dev': {remote_url}")
            continue
        remote_ref = f"refs/remotes/{remote_name}/{version}"
        if git_ref_exists(remote_ref, cwd=cwd):
            remote_candidates.append((remote_name != "origin", remote_name, f"{remote_name}/{version}", remote_url))

    if remote_candidates:
        _, _remote_name, base_ref, remote_url = min(remote_candidates)
        print(f"Using stable remote ref {base_ref} from {remote_url}")
        return base_ref

    local_ref = f"refs/heads/{version}"
    if git_ref_exists(local_ref, cwd=cwd):
        print(f"Using local stable ref {version} for commit message validation")
        return version

    print(f"Skipping commit message validation because stable ref {version} was not found")
    return ""


def get_invalid_commit_messages(base_ref, repo_root):
    rev_range = f"{base_ref}..HEAD"
    git_log = (
        subprocess.check_output(["git", "log", "--format=%H%x09%s", rev_range]).decode(sys.stdout.encoding).strip()
    )
    if not git_log:
        print(f"No new commits detected for commit message validation in range {rev_range}")
        return []

    invalid_commits = []
    for line in git_log.splitlines():
        sha, subject = line.split("\t", 1)
        errors = validate_commit_message_header(subject, repo_root=repo_root)
        if errors:
            invalid_commits.append({"sha": sha, "subject": subject, "errors": errors})
    return invalid_commits


def check_commit_messages_since_version(repo_root=None, version=None, scope=None):
    if repo_root is None:
        repo_root = get_repo()
    if version is None:
        version = os.environ.get("VERSION", "").strip()
    if scope is None:
        scope = os.environ.get(SCOPE_ENVVAR, "").strip()

    if not version and scope != SCOPE_LAST_COMMIT:
        print("Skipping commit message validation because VERSION was not defined")
        return True

    base_ref = resolve_commit_message_base_ref(version, scope=scope)
    if not base_ref:
        return True

    invalid_commits = get_invalid_commit_messages(base_ref, repo_root)
    if not invalid_commits:
        print(f"Commit message checks passed for range {base_ref}..HEAD")
        return True

    print(f"Commit message checks failed for range {base_ref}..HEAD")
    for invalid_commit in invalid_commits:
        print(f"{invalid_commit['sha'][:8]} {invalid_commit['subject']}")
        for error in invalid_commit["errors"]:
            print(f"  {error}")
    return False


def main_git_log():
    valid = check_commit_messages_since_version()
    if not valid:
        sys.exit(1)


def main():
    commit_msg_files = sys.argv[1:]
    if not commit_msg_files:
        print("Missing commit message file argument.")
        sys.exit(1)

    valid = True
    for commit_msg_file in commit_msg_files:
        if not check_commit_msg_file(commit_msg_file):
            valid = False
    if not valid:
        sys.exit(1)


if __name__ == "__main__":
    main()
