# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 119
proseWrap: always
semi: true
trailingComma: "es5"
xmlWhitespaceSensitivity: "strict"
xmlSelfClosingSpace: true

# Related to https://github.com/prettier/prettier/issues/7752#issuecomment-685451956
overrides:
  - files: "*.scss"
    options:
      trailingComma: "none"
