# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 119
proseWrap: always
semi: true
trailingComma: "es5"
xmlWhitespaceSensitivity: "strict"
xmlSelfClosingSpace: true
